name: heathbridge_lao
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  geolocator: ^11.1.0
  go_router: ^14.0.2
  hasura_connect: ^5.0.0+3
  latlong2: ^0.9.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  permission_handler: ^10.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/app-logo.png
    - assets/images/clinic-marker.png
    - assets/images/hospitol-marker.png
    - assets/images/pharmacy-marker.png
    # - assets/images/default-marker.png
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
