name: heathbridge_lao
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.0.2
  flutter_svg: ^2.0.10+1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  firebase_auth: ^4.17.8
  flutter_dotenv: ^5.1.0
  hasura_connect: ^5.0.0+3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/