// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ64vVRfu9fOm-OLe4ZEnpwpt7VLAX6Oo',
    appId: '1:279754083156:android:1d2ff7b643f3974491d6c1',
    messagingSenderId: '279754083156',
    projectId: 'finding-web',
    storageBucket: 'finding-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVHdaasr8uD-ftYuwEa7Hx82RZJbmikrU',
    appId: '1:279754083156:ios:2a645bcd6f8df42c91d6c1',
    messagingSenderId: '279754083156',
    projectId: 'finding-web',
    storageBucket: 'finding-web.appspot.com',
    iosBundleId: 'com.example.heathbridgeLao',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdSh3y1b9GXq9l4dBi0v9NEnIxo_t8dw',
    appId: '1:279754083156:web:e46b863573a9381f91d6c1',
    messagingSenderId: '279754083156',
    projectId: 'finding-web',
    authDomain: 'finding-web.firebaseapp.com',
    storageBucket: 'finding-web.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVHdaasr8uD-ftYuwEa7Hx82RZJbmikrU',
    appId: '1:279754083156:ios:2a645bcd6f8df42c91d6c1',
    messagingSenderId: '279754083156',
    projectId: 'finding-web',
    storageBucket: 'finding-web.appspot.com',
    iosBundleId: 'com.example.heathbridgeLao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkdSh3y1b9GXq9l4dBi0v9NEnIxo_t8dw',
    appId: '1:279754083156:web:7a357c19fd5e3bac91d6c1',
    messagingSenderId: '279754083156',
    projectId: 'finding-web',
    authDomain: 'finding-web.firebaseapp.com',
    storageBucket: 'finding-web.appspot.com',
  );

}